### PR TITLE
Scala 3.5.0

### PR DESCRIPTION
**Pull request by francisdb**
https://github.com/scala/scala3/releases/tag/3.5.0

### CODE REVIEW

**Comment by rparree** [comment]
I am not sure if you already found the problem, but when i run the commands locally i get 

```
❯ scala3-3.5.0/bin/scala -nocompdaemon test.scala
Deprecated option '-nocompdaemon' is ignored.
The script runner can no longer be picked as before.
Downloading compilation server 1.5.17-sc-2
Starting compilation server
Compiling project (Scala 3.5.0, JVM (17))
[error] ./test.scala:1:52
[error] Not found: dotty
[error] @main def main = println(s"Scala library version ${dotty.tools.dotc.config.Properties.versionNumberString}")
[error]                                                    ^^^^^
Error compiling project (Scala 3.5.0, JVM (17))

[error]        
```

**Comment by rparree** [comment]
changing the test code to 

```bash
echo '@main def main = println(s"Hello Scala")' > test.scala
```

Fixed the problem for me locally

**Comment by francisdb** [comment]
related to #208

**Comment by francisdb** [comment]
@rparree thanks for the hint, I'll fix this.

**Comment by francisdb** [comment]
Hmm, looks like this is an issue with `scala` being replaced by `scala-cli`

see also https://github.com/VirtusLab/scala-cli/issues/2758

**Comment by francisdb** [comment]
Guess this will have to wait for scala-cli fixes?

**Comment by rparree** [comment]
That problem i solved by placing the `Test.Scala` outside the root.

```
mkdir -p /test &&  echo '@main def main = println("Hello Scala")' > /test/test.scala
scala -nocompdaemon  /test/test.scala
```

**Comment by rparree** [comment]
I created a separate PR #299. I think it should work (local build runs)

```

**Comment by francisdb** [comment]
moved to #299

**Pull request closed without merging**
