### PR TITLE
scala 3.4.3

### PR DESCRIPTION
**Pull request by rparree**

### CODE REVIEW

**Comment by francisdb** [comment]
Thanks. Can you just replace 3.4.2 instead?

**Comment by francisdb** [comment]
Not sure what is going on with the build.

**Comment by rparree** [comment]
It only fails on:

- `scalaVersion`: `2.4.3`
- `javaTag`: [eclipse-temurin-alpine-21.0.2_13, eclipse-temurin-jammy-21.0.2_13 ]`

Let me have a look and see if i can find out what's the cause.

**Comment by rparree** [comment]
It seems the issue is straightforward: our internal Renovate bot detected new versions of Scala (3.4.3 and 3.5.0), but these versions haven't been released yet :)

Would you prefer to keep this PR open until 3.4.3 is officially released?

**Comment by francisdb** [comment]
Yes, we can keep it open. Strange that the other builds succeed with invalid archives 🤔

**Comment by francisdb** [comment]
Yes we can keep it open if the release is around the corner.

**Comment by francisdb** [comment]
thanks @rparree

**Pull request merged**
