### PR TITLE
add graalvm-community

### PR DESCRIPTION
**Pull request by btomala**
Since Graalvm 17 changed the versioning, the base images are available under [graalvm-community](https://github.com/graalvm/container/pkgs/container/graalvm-community) tag. 

I propose to add this image to have support for the latest Java 21 LTS version.

### CODE REVIEW

**Comment by francisdb** [comment]
Thanks a lot.

Can you also add it to the build matrix at `.github/workflows/build.yml` ?

**Comment by btomala** [comment]
Done, not sure how to test it though. Locally a build is working.

**Comment by francisdb** [comment]
https://github.com/sbt/docker-sbt/actions/runs/6967041092

**Review by francisdb — APPROVED** [review]

**Comment by francisdb** [comment]
Thanks a lot!

**Pull request merged**
